### ISSUE TITLE
config limits of inotify watches

### ISSUE THREAD

**Issue by maciejskorski** [gitguesser/gitguesser#21]
Due to the React overhead in system events to be tracked, the frontend container doesn't get up occasionally 
```console
gitguesser-frontend-1  | Error: ENOSPC: System limit for number of file watchers reached, watch '/frontend/public/index.html'
```
When the limit are too low
```console
(.mlflow) (base) maciej.skorski@kaggle-cpu-maciej:~$ cat /proc/sys/fs/inotify/max_user_watches
8192
```
can be [raised as suggested on SO](https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached) to
```
fs.inotify.max_user_watches=524288
```
This fixes the issue, but is this safe / harmless? What is a good value for this app?

**Comment by lukaszsmolinski** [comment]
This project uses `create-react-app`, and its [docs](https://create-react-app.dev/docs/troubleshooting/#npm-start-fail-due-to-watch-error) suggest increasing the `fs.inotify.max_user_watches` value when encountering such an error. A similar solution can also be found in the `webpack` [docs](https://webpack.js.org/configuration/watch/#not-enough-watchers).

The suggested value is the maximum possible, and it should be [safe](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached/13757#13757). This value is set as the default in the Linux distribution I am using.

**Comment by maciejskorski** [comment]
Thx!
